# Generated by Django 3.2.12 on 2023-03-25 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0002_pedido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
