FROM ubuntu:18.04
# ENV TZ=Europe/Moscow
# RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone
MAINTAINER devsi.pf@gmail.com
RUN apt-get update
RUN apt-get install -y python3.8
#RUN pip install django
CMD ["echo", "olá estou no meu container"]