# Generated by Django 4.1.3 on 2022-11-23 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teste', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='usuario',
            index=models.Index(fields=['primeiro_nome', 'ultimo_nome'], name='primeiro_nome_usuario'),
        ),
    ]
