# Generated by Django 4.1.1 on 2022-09-17 00:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sinais', '0002_historio'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Historio',
            new_name='Historico',
        ),
    ]
