# Generated by Django 3.2.12 on 2023-04-03 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0002_pedido'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='valor_pago',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
